/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tasktoo;

import javax.xml.parsers.DocumentBuilderFactory;
import javax.swing.plaf.synth.Region;
import javax.xml.parsers.DocumentBuilder;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;
import org.w3c.dom.Element;
import java.io.File;
import java.io.InputStream;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
            // Use ClassLoader to load the XML file as a resource
            ClassLoader classLoader = App.class.getClassLoader();
            InputStream xmlFile = classLoader.getResourceAsStream("data.xml");

            if (xmlFile == null) {
                throw new IllegalArgumentException("file not found! " + "sample.xml");
            }

            // Create a DocumentBuilderFactory
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();

            // Create a DocumentBuilder
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();

            // Parse the XML file and build the Document
            Document doc = dBuilder.parse(xmlFile);

            // Normalize the XML structure
            doc.getDocumentElement().normalize();

            System.out.println("Root element: " + doc.getDocumentElement().getNodeName());

            // Get all employee nodes
            NodeList nodeList = doc.getElementsByTagName("record");

            // Loop through all employee nodes
            for (int i = 0; i < nodeList.getLength(); i++) {
                Node node = nodeList.item(i);

                if (node.getNodeType() == Node.ELEMENT_NODE) {
                    Element element = (Element) node;

                    // Get the value of the id, name, and position fields
                    String name = element.getElementsByTagName("name").item(0).getTextContent();
                    String postalZip = element.getElementsByTagName("postalZip").item(0).getTextContent();
                    String region = element.getElementsByTagName("region").item(0).getTextContent();
                    String country = element.getElementsByTagName("country").item(0).getTextContent();
                    String address = element.getElementsByTagName("address").item(0).getTextContent();
                    String list = element.getElementsByTagName("list").item(0).getTextContent();

                    // Print the values
                    System.out.println("Name: " + name);
                    System.out.println("Postal Zip: " + postalZip);
                    System.out.println("Region: " + region);
                    System.out.println("Country: " + country);
                    System.out.println("Address: " + address);
                    System.out.println("List: " + list);
                    System.out.println("--------------");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
